FROM alpine:3.5

ENV GOPATH=/go PATH=$PATH:/go/bin

RUN mkdir -p /go/bin
RUN apk update
RUN apk add go curl git dumb-init su-exec libc-dev glide

COPY glide.yaml glide.lock /go/src/github.com/atombender/gce-metadata-exporter/
RUN (cd /go/src/github.com/atombender/gce-metadata-exporter && glide install --strip-vendor)

COPY *.go /go/src/github.com/atombender/gce-metadata-exporter/
RUN go build -o /usr/bin/gce-metadata-exporter github.com/atombender/gce-metadata-exporter
